[project]
name = "audio"
version = "0.1.0"
description = "Audio capture application using ffmpeg"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [] # ffmpeg is an external CLI tool, not a Python library here

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
